import Navbar from "@/components/Navbar";
import Sidebar from "@/components/Sidebar";
import { DM_Sans } from "next/font/google";
import "./globals.css";

const inter = DM_Sans({ subsets: ["latin"] });

export const metadata = {
  title: "Hermes",
  description: "Generated by Hermes",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className + " background"}>
        <div>
          <Navbar />
          <div className="flex">
            <Sidebar />
            <div className="w-full">{children}</div>
          </div>
        </div>
      </body>
    </html>
  );
}
