import Navbar from "@/components/Navbar";
import Sidebar from "@/components/Sidebar";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Hermes",
  description: "Generated by Hermes",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className + " background"}>
        <div className="flex ">
          <Sidebar />
          <div>
            <Navbar />
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
